baseURL = 'https://robertwetzler.github.io/blog/'
languageCode = 'en-us'
title = "Robert's Roblog"
theme = 'PaperMod'

[params]
  description = "A simple blog built with Hugo"
  author = "Robert Wetzler"
  showReadingTime = true
  showShareButtons = true
  showPostNavLinks = true

  [params.homeInfoParams]
    Title = "Hello! I'm Robert ðŸ‘‹"
    Content = """
I'm a passionate software engineer at Microsoft working on Azure Storage. I love building distributed systems, tinkering with robotics and astrophotography, and exploring new technologies.

When I'm not writing code, you might find me working on personal projects like social apps or building camera gimbals that track stars.

**[Check out my resume â†’](/blog/resume/)**
"""

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 4
